version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5432:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
